;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-horizontal-space
        downcase-region
        handle-switch-frame
        indent-for-tab-command
        kill-region
        kill-sexp
        org-force-self-insert
        orgtbl-hijacker-command-101
        orgtbl-hijacker-command-103
        orgtbl-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ekr-recompile
        projectile-find-file
        switch-to-buffer
        toggle-frame-fullscreen
        ))
