# whole, diff, diff-fenced, udiff
# In architect mode: editor-diff, editor-whole

- name: github_copilot/gpt-4.1
  edit_format: editor-diff
#   extra_params:
#     max_tokens: 80000
#     extra_headers:
#       User-Agent: GithubCopilot/1.155.0
#       Editor-Plugin-Version: copilot/1.155.0
#       Editor-Version: vscode/1.85.1
#       Copilot-Integration-Id: vscode-chat

- name: github_copilot/gpt-5
  edit_format: editor-diff
#   extra_params:
#     # max_tokens: 80000
#     extra_headers:
#       User-Agent: GithubCopilot/1.155.0
#       Editor-Plugin-Version: copilot/1.155.0
#       Editor-Version: vscode/1.85.1
#       Copilot-Integration-Id: vscode-chat

- name: aider/extra_params
  extra_params:
    extra_headers:
      Editor-Version: vscode/42

- name: github_copilot/claude-opus-4.6
  edit_format: editor-diff

- name: github_copilot/claude-sonnet-4.6
  edit_format: editor-diff

- name: github_copilot/claude-sonnet-4.6
  edit_format: editor-diff
